clc;
clear all;
T=1;
r=.05;
sig=.3;
K=100;
n=500;
s0=80:5:120;
euputa=zeros(length(s0),1);
amputa=zeros(length(s0),1);
euputb=zeros(length(s0),1);
amputb=zeros(length(s0),1);
euputc=zeros(length(s0),1);
amputc=zeros(length(s0),1);
euputd=zeros(length(s0),1);
amputd=zeros(length(s0),1);

for i=1:length(s0);
    euputa(i)=putBinomEuroa(s0(i),K,r,T,sig,n);
    amputa(i)=putBinomAma(s0(i),K,r,T,sig,n);
    euputb(i)=putBinomEurob(s0(i),K,r,T,sig,n);
    amputb(i)=putBinomAmb(s0(i),K,r,T,sig,n);
    euputc(i)=putBinomEuroc(s0(i),K,r,T,sig,n);
    amputc(i)=putBinomAmc(s0(i),K,r,T,sig,n);
    euputd(i)=putBinomEurod(s0(i),K,r,T,sig,n);
    amputd(i)=putBinomAmd(s0(i),K,r,T,sig,n);
end;
subplot(4,1,1);
plot( s0,[euputa amputa]);
h1 = legend('eu put a','am put a',4);
set(h1,'Interpreter','none');
subplot(4,1,2);
plot( s0,[euputb amputb]);
h2 = legend('eu put b','am put b',4);
set(h2,'Interpreter','none');
subplot(4,1,3);
plot( s0,[euputc amputc]);
h3 = legend('eu put c','am put c',4);
set(h3,'Interpreter','none');
subplot(4,1,4);
plot( s0,[euputb amputb]);
h4 = legend('eu put d','am put d',4);
set(h4,'Interpreter','none');